reference: http://www.objc.io/issue-6/travis-ci.html
language: objective-c
cache: bundler
script:
- xctool test -workspace Example/UIKit+Material.xcworkspace -scheme UIKit+Material -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
